# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 100 / Edge 103
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cypress and verify
        run:
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress tests ( Chrome )
        run: npm run test_chrome_dashboard
        continue-on-error: false

      - name: Run Cypress tests ( Edge )
        run: npm run test_edge_dashboard
        continue-on-error: false
        

