
name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 100
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cypress and verify
        run:
          npm ci
          $(npm bin)/cypress verify
          npm cache clean
          
      - name: Run Cypress tests ( Chrome )
        run: npm run test_chrome_dashboard
        continue-on-error: false
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
